Vagrant.configure("2") do |config|

config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # VM 1
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/trusty64"
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.33.10"

  end

  # VM 2
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/trusty64"
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.33.20"

    vm2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y git
      git config --global user.name "BelousWladislaw"
      git config --global user.email "wwwwladikby059@gmail.com"

      git clone https://github.com/BelousWladislaw/OSMU

      cat OSMU/lab_1/task_1/git/module2.txt
    SHELL
  end
end