Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.box = "ubuntu/trusty64"

  # Запрос количества виртуальных машин
  puts "Введите количество виртуальных машин (1-253): "
  vm_count = Integer(STDIN.gets)

  unless (1..253).include?(vm_count)
    puts "Неверное количество виртуальных машин. Пожалуйста, введите число от 1 до 253."
    exit
  end

  # Запуск виртуальной машины веб-сервера
  config.vm.define "webserver" do |webserver|
    webserver.vm.hostname = "webserver"
    webserver.vm.network "forwarded_port", guest: 80, host: 8080
    webserver.vm.network "private_network", ip: "192.168.70.10"
    webserver.vm.provider "virtualbox" do |vb|
      vb.name = "webserver"
    end
    # Настройка веб-сервера
    webserver.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx
      sudo mkdir -p /var/www/html/
      echo "Добро пожаловать на веб-сервер!" | sudo tee /var/www/html/index.html
    SHELL
  end

  if vm_count > 1
    # Запуск виртуальных машин Tomcat
    (1..(vm_count - 1)).each do |i|
      config.vm.define "tomcat#{i}" do |tomcat|
        tomcat.vm.hostname = "tomcat#{i}"
        tomcat.vm.network "private_network", ip: "192.168.70.#{i + 10}"
        tomcat.vm.provider "virtualbox" do |vb|
          vb.name = "tomcat#{i}"
        end
        # Настройка виртуальных машин Tomcat
        tomcat.vm.provision "shell", inline: <<-SHELL
	  #export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  	  #export JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
 	  #source ~/.bashrc
	  echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> ~/.bashrc
   	  echo "export JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre" >> ~/.bashrc
  	  source ~/.bashrc
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
          wget --no-check-certificate https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.107/bin/apache-tomcat-7.0.107.tar.gz
          tar -xf apache-tomcat-7.0.107.tar.gz
          sudo mkdir -p /opt/tomcat7
          sudo mv apache-tomcat-7.0.107/* /opt/tomcat7/
          sudo chown -R vagrant:vagrant /opt/tomcat7
          sudo sed -i 's/Connector port="8080"/Connector port="8080" address="0.0.0.0"/' /opt/tomcat7/conf/server.xml
          echo "Добро пожаловать на Tomcat на #{tomcat.vm.hostname}!" > /opt/tomcat7/webapps/ROOT/index.jsp
          sudo /opt/tomcat7/bin/startup.sh
        SHELL
      end
    end
  end
end